create table TICKET (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME varchar(100) NOT NULL,
  DESCRICAO varchar(400) NOT NULL,
  DATA date not null,
  CIDADE_ID BIGINT NOT NULL,
  FORNECEDOR_ID BIGINT NOT NULL,
  foreign key TICKET_FORNECEDOR_ID (FORNECEDOR_ID) references FORNECEDOR(ID)
) ENGINE=InnoDB;